version: '2'
services:
  jhtest-app:
    image: jhtest
    environment:
      - _JAVA_OPTIONS=-Xmx512m -Xms256m
      - SPRING_PROFILES_ACTIVE=prod,swagger
      - MANAGEMENT_METRICS_EXPORT_PROMETHEUS_ENABLED=true
      - SPRING_DATA_MONGODB_URI=mongodb://jhtest-mongodb:27017
      - SPRING_DATA_MONGODB_DATABASE=jhtest
      - JHIPSTER_SLEEP=30 # gives time for other services to boot before the application
      - SPRING_DATA_JEST_URI=http://jhtest-elasticsearch:9200
      - SPRING_ELASTICSEARCH_REST_URIS=http://jhtest-elasticsearch:9200
    ports:
      - 8080:8080
  jhtest-mongodb:
    extends:
      file: mongodb.yml
      service: jhtest-mongodb
  jhtest-elasticsearch:
    extends:
      file: elasticsearch.yml
      service: jhtest-elasticsearch
